import React, { useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import * as Print from "expo-print";
import { HeaderStatusBar } from "../components/HeaderStatusBar";
import { mobileStorage } from "../lib/mobile-storage";
import { mobileTheme } from "../lib/mobile-theme";

type Receipt = { retailOrgName: string; storeName: string; storeAddress?: string | null; transactionNo: string; completedAt: string; cashierCode: string; currencyCode: string; customerName: string; subtotalAmount: number; discountAmount: number; taxAmount: number; totalAmount: number; paidAmount: number; changeAmount: number; receiptHeader?: string | null; receiptFooter?: string | null; lines: Array<{ productCode: string; productName: string; quantity: number; sellingUnitOfMeasure: string; unitPrice: number; lineTotal: number }>; payments: Array<{ tenderMethodName: string | null; method: string; amount: number; reference: string | null }> };

export default function ReceiptScreen() {
  const [receipt, setReceipt] = useState<Receipt | null>(null);
  const [ready, setReady] = useState(false);
  const insets = useSafeAreaInsets();
  useEffect(() => {
    void mobileStorage.getLastReceipt<Receipt>()
      .then((saved) => setReceipt(saved && Array.isArray(saved.lines) && Array.isArray(saved.payments) ? saved : null))
      .catch(() => setReceipt(null))
      .finally(() => setReady(true));
  }, []);
  if (ready && !receipt) return <View style={styles.loading}><Text>No saved receipt is available.</Text><TouchableOpacity accessibilityRole="button" onPress={() => router.dismissTo("/")}><Text style={styles.doneText}>Back to dashboard</Text></TouchableOpacity></View>;
  if (!receipt) return <View style={styles.loading}><ActivityIndicator color={mobileTheme.primary} /><Text>Loading receipt…</Text></View>;
  const money = (value: number) => `${receipt.currencyCode} ${Number(value).toFixed(2)}`;
  const printReceipt = async () => {
    const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character] || character));
    const lineHtml = receipt.lines.map((line) => `<tr><td>${escape(line.quantity)} × ${escape(line.productName)}<small>${escape(line.sellingUnitOfMeasure)} @ ${escape(money(line.unitPrice))}</small></td><td>${escape(money(line.lineTotal))}</td></tr>`).join("");
    const paymentHtml = receipt.payments.map((payment) => `<tr><td>${escape(payment.tenderMethodName || payment.method)}</td><td>${escape(money(payment.amount))}</td></tr>`).join("");
    await Print.printAsync({ html: `<!doctype html><html><head><meta name="viewport" content="width=device-width"><style>@page{margin:8mm}body{font-family:monospace;font-size:11px;color:#000;max-width:76mm;margin:auto}h1,h2,p{text-align:center;margin:3px}table{width:100%;border-collapse:collapse}td{padding:4px 0;border-bottom:1px dashed #aaa}td:last-child{text-align:right;font-weight:bold}small{display:block;color:#555}.total{font-size:15px;font-weight:bold}</style></head><body><h1>${escape(receipt.retailOrgName)}</h1><h2>${escape(receipt.storeName)}</h2><p>${escape(receipt.storeAddress || "")}</p><p>Receipt ${escape(receipt.transactionNo)}<br>${escape(new Date(receipt.completedAt).toLocaleString())}<br>Customer: ${escape(receipt.customerName)}</p><table>${lineHtml}<tr><td>Subtotal</td><td>${escape(money(receipt.subtotalAmount))}</td></tr><tr><td>Tax</td><td>${escape(money(receipt.taxAmount))}</td></tr><tr class="total"><td>TOTAL</td><td>${escape(money(receipt.totalAmount))}</td></tr>${paymentHtml}${receipt.changeAmount > 0 ? `<tr><td>Change</td><td>${escape(money(receipt.changeAmount))}</td></tr>` : ""}</table><p>${escape(receipt.receiptFooter || "Thank you for shopping with us.")}</p></body></html>` });
  };
  const share = async () => {
    const lines = receipt.lines.map((line) => `${line.quantity} × ${line.productName} — ${money(line.lineTotal)}`).join("\n");
    await Share.share({ message: `${receipt.retailOrgName}\n${receipt.storeName}\nReceipt ${receipt.transactionNo}\n${lines}\nTOTAL: ${money(receipt.totalAmount)}\nThank you.` });
  };
  return <View style={styles.container}><HeaderStatusBar /><View style={styles.topBar}><TouchableOpacity onPress={() => router.dismissTo("/")}><Ionicons name="close" size={24} color={mobileTheme.textColor} /></TouchableOpacity><Text style={styles.title}>Receipt</Text><TouchableOpacity onPress={share}><Ionicons name="share-social-outline" size={23} color={mobileTheme.primary} /></TouchableOpacity></View><ScrollView contentContainerStyle={[styles.content, { paddingBottom: Math.max(insets.bottom, 20) }]}><View style={styles.paper}><Text style={styles.org}>{receipt.retailOrgName}</Text><Text style={styles.store}>{receipt.storeName}</Text>{receipt.storeAddress && <Text style={styles.muted}>{receipt.storeAddress}</Text>}<View style={styles.divider} /><Text style={styles.receiptNo}>{receipt.transactionNo}</Text><Text style={styles.muted}>{new Date(receipt.completedAt).toLocaleString()} · {receipt.cashierCode}</Text><Text style={styles.muted}>Customer: {receipt.customerName}</Text><View style={styles.divider} />{receipt.lines.map((line, index) => <View key={`${line.productCode}-${index}`} style={styles.line}><View style={{ flex: 1 }}><Text style={styles.lineName}>{line.productName}</Text><Text style={styles.muted}>{line.quantity} {line.sellingUnitOfMeasure} × {money(line.unitPrice)}</Text></View><Text style={styles.lineTotal}>{money(line.lineTotal)}</Text></View>)}<View style={styles.divider} /><Row label="Subtotal" value={money(receipt.subtotalAmount)} /><Row label="Discount" value={money(receipt.discountAmount)} /><Row label="Tax" value={money(receipt.taxAmount)} /><Row label="TOTAL" value={money(receipt.totalAmount)} strong />{receipt.payments.map((payment, index) => <Row key={index} label={payment.tenderMethodName || payment.method} value={money(payment.amount)} />)}{receipt.changeAmount > 0 && <Row label="Change" value={money(receipt.changeAmount)} strong />}<View style={styles.divider} /><Text style={styles.footer}>{receipt.receiptFooter || "Thank you for shopping with us."}</Text></View><TouchableOpacity style={styles.printButton} onPress={printReceipt}><Ionicons name="print" size={19} color="#fff" /><Text style={styles.shareText}>Print Receipt</Text></TouchableOpacity><TouchableOpacity style={styles.shareButton} onPress={share}><Ionicons name="share-social" size={19} color="#fff" /><Text style={styles.shareText}>Share Receipt</Text></TouchableOpacity><TouchableOpacity style={styles.doneButton} onPress={() => router.dismissTo("/")}><Text style={styles.doneText}>Done</Text></TouchableOpacity></ScrollView></View>;
}
function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <View style={styles.row}><Text style={strong ? styles.strong : styles.rowLabel}>{label}</Text><Text style={strong ? styles.strong : styles.rowValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: mobileTheme.screenBackground }, loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10 }, topBar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 14, backgroundColor: mobileTheme.surfaceBackground }, title: { fontSize: 18, fontWeight: "900", color: mobileTheme.textColor }, content: { padding: 16, gap: 12 }, paper: { backgroundColor: "#fff", padding: 20, borderRadius: 12, gap: 8, ...mobileTheme.shadowSmall }, org: { textAlign: "center", fontSize: 19, fontWeight: "900" }, store: { textAlign: "center", fontSize: 15, fontWeight: "700" }, muted: { color: mobileTheme.mutedText, fontSize: 12 }, divider: { borderTopWidth: 1, borderStyle: "dashed", borderColor: mobileTheme.borderColor, marginVertical: 7 }, receiptNo: { fontSize: 15, fontWeight: "900" }, line: { flexDirection: "row", gap: 10 }, lineName: { fontSize: 13, fontWeight: "700" }, lineTotal: { fontWeight: "800" }, row: { flexDirection: "row", justifyContent: "space-between" }, rowLabel: { color: mobileTheme.mutedText }, rowValue: { color: mobileTheme.textColor }, strong: { fontSize: 16, fontWeight: "900", color: mobileTheme.textColor }, footer: { textAlign: "center", marginTop: 8, color: mobileTheme.mutedText }, printButton: { flexDirection: "row", justifyContent: "center", gap: 8, padding: 14, borderRadius: 12, backgroundColor: mobileTheme.accent }, shareButton: { flexDirection: "row", justifyContent: "center", gap: 8, padding: 14, borderRadius: 12, backgroundColor: mobileTheme.primary }, shareText: { color: "#fff", fontWeight: "800" }, doneButton: { alignItems: "center", padding: 13 }, doneText: { color: mobileTheme.primary, fontWeight: "800" } });
