ALTER TABLE "SyncNode"
ADD COLUMN "autoSyncEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "syncIntervalMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN "syncActiveFromMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "syncActiveToMinutes" INTEGER NOT NULL DEFAULT 1440,
ADD COLUMN "syncJitterSeconds" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "syncBackoffBaseSeconds" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN "syncBackoffMaxSeconds" INTEGER NOT NULL DEFAULT 900,
ADD COLUMN "nextScheduledSyncAt" TIMESTAMP(3),
ADD COLUMN "lastManualSyncAt" TIMESTAMP(3),
ADD COLUMN "lastAutoSyncAt" TIMESTAMP(3);
