export declare const RecordStatus: Readonly<Record<string, string>>;
export type RecordStatus = string;
export declare const UserAccountStatus: Readonly<Record<string, string>>;
export type UserAccountStatus = string;
export declare const CustomerType: Readonly<Record<string, string>>;
export type CustomerType = string;
export declare const CustomerAccountEntryType: Readonly<Record<string, string>>;
export type CustomerAccountEntryType = string;
export declare const SyncNodeType: Readonly<Record<string, string>>;
export type SyncNodeType = string;
export declare const SyncDirection: Readonly<Record<string, string>>;
export type SyncDirection = string;
export declare const SyncEventStatus: Readonly<Record<string, string>>;
export type SyncEventStatus = string;
export declare const SecurityLogKind: Readonly<Record<string, string>>;
export type SecurityLogKind = string;
export declare const SecurityLogSeverity: Readonly<Record<string, string>>;
export type SecurityLogSeverity = string;
export declare const SyncOperatorActionType: Readonly<Record<string, string>>;
export type SyncOperatorActionType = string;
export declare const LocationType: Readonly<Record<string, string>>;
export type LocationType = string;
export declare const InventoryMovementType: Readonly<Record<string, string>>;
export type InventoryMovementType = string;
export declare const SerialInventoryStatus: Readonly<Record<string, string>>;
export type SerialInventoryStatus = string;
export declare const PosShiftStatus: Readonly<Record<string, string>>;
export type PosShiftStatus = string;
export declare const PosTransactionType: Readonly<Record<string, string>>;
export type PosTransactionType = string;
export declare const PosTransactionLineIntent: Readonly<Record<string, string>>;
export type PosTransactionLineIntent = string;
export declare const PosTransactionStatus: Readonly<Record<string, string>>;
export type PosTransactionStatus = string;
export declare const SalesOrderStatus: Readonly<Record<string, string>>;
export type SalesOrderStatus = string;
export declare const PaymentMethod: Readonly<Record<string, string>>;
export type PaymentMethod = string;
export declare const PaymentGatewayProvider: Readonly<Record<string, string>>;
export type PaymentGatewayProvider = string;
export declare const PaymentGatewayMode: Readonly<Record<string, string>>;
export type PaymentGatewayMode = string;
export declare const PaymentGatewayStatus: Readonly<Record<string, string>>;
export type PaymentGatewayStatus = string;
export declare const GlAccountType: Readonly<Record<string, string>>;
export type GlAccountType = string;
export declare const GlNormalBalance: Readonly<Record<string, string>>;
export type GlNormalBalance = string;
export declare const GlJournalStatus: Readonly<Record<string, string>>;
export type GlJournalStatus = string;
export declare const OperatingExpenseStatus: Readonly<Record<string, string>>;
export type OperatingExpenseStatus = string;
export declare const PromotionDiscountType: Readonly<Record<string, string>>;
export type PromotionDiscountType = string;
export declare const PromotionTargetScope: Readonly<Record<string, string>>;
export type PromotionTargetScope = string;
export declare const ProductType: Readonly<Record<string, string>>;
export type ProductType = string;
export declare const PurchaseOrderStatus: Readonly<Record<string, string>>;
export type PurchaseOrderStatus = string;
export declare const PurchaseOrderClosureReason: Readonly<Record<string, string>>;
export type PurchaseOrderClosureReason = string;
export declare const SupplierClaimStatus: Readonly<Record<string, string>>;
export type SupplierClaimStatus = string;
export declare const SupplierClaimReason: Readonly<Record<string, string>>;
export type SupplierClaimReason = string;
export declare const SupplierReturnStatus: Readonly<Record<string, string>>;
export type SupplierReturnStatus = string;
export declare const SupplierReturnReason: Readonly<Record<string, string>>;
export type SupplierReturnReason = string;
export declare const StockCountSessionStatus: Readonly<Record<string, string>>;
export type StockCountSessionStatus = string;
export declare const InterStoreTransferOrigin: Readonly<Record<string, string>>;
export type InterStoreTransferOrigin = string;
export declare const InterStoreTransferStatus: Readonly<Record<string, string>>;
export type InterStoreTransferStatus = string;
